name: 'Selected Daemons'
description: 'Validate steps daemons'

inputs:
  selected_daemons:
    required: true
  step:
    required: true
outputs:
  daemons:
    description: "Build Daemons"
  
runs:
  using: 'node20'
  main: 'index.js'