name: Deploy For Downtime

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      can_i_deploy:
        description: "Can I Deploy?"
        required: true
        type: choice
        options:
          - "no"
          - "yes"
      selected_daemons:
        description: "Daemons detail"
        required: true
        type: string
jobs:
  first_daemon:
    runs-on: ubuntu-latest
    name: Buscando primeiros Daemons
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Slavebook validation
        uses: ./ruby
        with:
          selected_daemons: ${{ inputs.selected_daemons }}
          step: "one"
        id: selected_daemons
      - name: first daemons
        run: echo "PRIMEIROS DAEMONS ${{ steps.selected_daemons.outputs.daemons}}"

  second_daemon:
    runs-on: ubuntu-latest
    needs:
      - first_daemon
    name: Buscando Restante Daemons
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Slavebook validation
        uses: ./ruby
        with:
          selected_daemons: ${{ inputs.selected_daemons }}
          step: "two"
        id: selected_daemons

      - name: second daemons
        run: echo "SEGUNDO DAEMONS ${{ steps.selected_daemons.outputs.daemons }}"
